/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  /**
   * / Upsert a batch of records (insert or overwrite by id).
   */
  'batchUpsert' : ActorMethod<
    [string, Array<{ 'id' : string, 'data' : string }>],
    { 'ok' : boolean, 'err' : string, 'count' : bigint }
  >,
  /**
   * / Create a new record. Fails if the id already exists.
   */
  'createRecord' : ActorMethod<
    [string, string, string],
    { 'ok' : boolean, 'err' : string }
  >,
  /**
   * / Delete an entire collection. Returns number of records removed.
   */
  'deleteCollection' : ActorMethod<
    [string],
    { 'ok' : boolean, 'count' : bigint }
  >,
  /**
   * / Delete a record by id.
   */
  'deleteRecord' : ActorMethod<
    [string, string],
    { 'ok' : boolean, 'err' : string }
  >,
  /**
   * / Export all data for backup. Returns array of (collection, [(id, data)]).
   */
  'exportAll' : ActorMethod<[], Array<[string, Array<[string, string]>]>>,
  /**
   * / Return changelog entries since a given timestamp (nanoseconds).
   * / Pass 0 to get all entries.
   */
  'getChangelog' : ActorMethod<[bigint], Array<string>>,
  /**
   * / Return count per collection.
   */
  'getCounts' : ActorMethod<[], Array<[string, bigint]>>,
  /**
   * / Get a single record by id. Returns null if not found.
   */
  'getRecord' : ActorMethod<[string, string], [] | [string]>,
  /**
   * / Import all data from a backup. Merges (upserts) all records.
   */
  'importAll' : ActorMethod<
    [Array<[string, Array<[string, string]>]>],
    { 'ok' : boolean, 'count' : bigint }
  >,
  /**
   * / List all records in a collection as an array of JSON strings.
   */
  'listRecords' : ActorMethod<[string], Array<string>>,
  /**
   * / Paginated list. offset is 0-based.
   */
  'listRecordsPaginated' : ActorMethod<
    [string, bigint, bigint],
    { 'total' : bigint, 'records' : Array<string> }
  >,
  /**
   * / Health check.
   */
  'ping' : ActorMethod<[], string>,
  /**
   * / Update an existing record. Returns err if not found.
   */
  'updateRecord' : ActorMethod<
    [string, string, string],
    { 'ok' : boolean, 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];