/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'batchUpsert' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'createRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'fetchAll' : IDL.Func([], [IDL.Text], ['query']),
  'getChangelog' : IDL.Func([], [IDL.Text], ['query']),
  'getCounts' : IDL.Func([], [IDL.Text], ['query']),
  'getRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'listRecords' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'ping' : IDL.Func([], [IDL.Text], ['query']),
  'replaceCollection' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'updateRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'upsertRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'batchUpsert' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'createRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'fetchAll' : IDL.Func([], [IDL.Text], ['query']),
    'getChangelog' : IDL.Func([], [IDL.Text], ['query']),
    'getCounts' : IDL.Func([], [IDL.Text], ['query']),
    'getRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
    'listRecords' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'ping' : IDL.Func([], [IDL.Text], ['query']),
    'replaceCollection' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'updateRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'upsertRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };