/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'batchUpsert' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Record({ 'id' : IDL.Text, 'data' : IDL.Text }))],
      [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Text, 'count' : IDL.Nat })],
      [],
    ),
  'createRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteCollection' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'count' : IDL.Nat })],
      [],
    ),
  'deleteRecord' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'exportAll' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))))],
      ['query'],
    ),
  'getChangelog' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'importAll' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))))],
      [IDL.Record({ 'ok' : IDL.Bool, 'count' : IDL.Nat })],
      [],
    ),
  'listRecords' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'listRecordsPaginated' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'records' : IDL.Vec(IDL.Text) })],
      ['query'],
    ),
  'ping' : IDL.Func([], [IDL.Text], ['query']),
  'updateRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'batchUpsert' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Record({ 'id' : IDL.Text, 'data' : IDL.Text }))],
        [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Text, 'count' : IDL.Nat })],
        [],
      ),
    'createRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteCollection' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'count' : IDL.Nat })],
        [],
      ),
    'deleteRecord' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'exportAll' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))))],
        ['query'],
      ),
    'getChangelog' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getRecord' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'importAll' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))))],
        [IDL.Record({ 'ok' : IDL.Bool, 'count' : IDL.Nat })],
        [],
      ),
    'listRecords' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'listRecordsPaginated' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'records' : IDL.Vec(IDL.Text) })],
        ['query'],
      ),
    'ping' : IDL.Func([], [IDL.Text], ['query']),
    'updateRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };