/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceScanRecord {
  'id' : bigint,
  'studentId' : string,
  'scannedBy' : string,
  'timestamp' : Time,
  'deviceRole' : string,
}
export interface CredentialRecord {
  'userId' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'hashedPassword' : string,
}
export interface NotificationChannel {
  'rcs' : boolean,
  'sms' : boolean,
  'push' : boolean,
  'whatsapp' : boolean,
  'email' : boolean,
  'inApp' : boolean,
}
export interface NotificationRecipientGroup {
  'students' : boolean,
  'teachers' : boolean,
  'staff' : boolean,
  'admins' : boolean,
  'parents' : boolean,
}
export interface NotificationRuleRecord {
  'id' : bigint,
  'timing' : string,
  'createdAt' : Time,
  'recipientGroups' : NotificationRecipientGroup,
  'channels' : NotificationChannel,
  'isActive' : boolean,
  'updatedAt' : Time,
  'eventType' : string,
}
export interface PaymentRecord {
  'id' : bigint,
  'studentId' : string,
  'paymentGateway' : string,
  'timestamp' : Time,
  'monthsPaid' : Array<string>,
  'amount' : bigint,
  'receiptNumber' : string,
}
export interface RCSMessageRecord {
  'id' : bigint,
  'status' : string,
  'recipient' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'createCredentialRecord' : ActorMethod<[string, string], undefined>,
  'createNotificationRuleRecord' : ActorMethod<
    [string, string, NotificationChannel, NotificationRecipientGroup, boolean],
    bigint
  >,
  'createPaymentRecord' : ActorMethod<
    [string, bigint, Array<string>, string, string],
    bigint
  >,
  'getAttendanceScanRecord' : ActorMethod<
    [bigint],
    [] | [AttendanceScanRecord]
  >,
  'getAttendanceScanRecords' : ActorMethod<[], Array<AttendanceScanRecord>>,
  'getCredentialRecord' : ActorMethod<[string], [] | [CredentialRecord]>,
  'getCredentialRecords' : ActorMethod<[], Array<CredentialRecord>>,
  'getNotificationRuleRecord' : ActorMethod<
    [bigint],
    [] | [NotificationRuleRecord]
  >,
  'getNotificationRuleRecords' : ActorMethod<[], Array<NotificationRuleRecord>>,
  'getPaymentRecord' : ActorMethod<[bigint], [] | [PaymentRecord]>,
  'getPaymentRecords' : ActorMethod<[], Array<PaymentRecord>>,
  'getRCSMessageRecord' : ActorMethod<[bigint], [] | [RCSMessageRecord]>,
  'getRCSMessageRecords' : ActorMethod<[], Array<RCSMessageRecord>>,
  'logAttendanceScan' : ActorMethod<[string, string, string], bigint>,
  'logRCSMessage' : ActorMethod<[string, string, string], bigint>,
  'resetPassword' : ActorMethod<[string, string], undefined>,
  'updateNotificationRuleRecord' : ActorMethod<
    [
      bigint,
      string,
      string,
      NotificationChannel,
      NotificationRecipientGroup,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];