/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NotificationChannel = IDL.Record({
  'rcs' : IDL.Bool,
  'sms' : IDL.Bool,
  'push' : IDL.Bool,
  'whatsapp' : IDL.Bool,
  'email' : IDL.Bool,
  'inApp' : IDL.Bool,
});
export const NotificationRecipientGroup = IDL.Record({
  'students' : IDL.Bool,
  'teachers' : IDL.Bool,
  'staff' : IDL.Bool,
  'admins' : IDL.Bool,
  'parents' : IDL.Bool,
});
export const Time = IDL.Int;
export const AttendanceScanRecord = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Text,
  'scannedBy' : IDL.Text,
  'timestamp' : Time,
  'deviceRole' : IDL.Text,
});
export const CredentialRecord = IDL.Record({
  'userId' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'hashedPassword' : IDL.Text,
});
export const NotificationRuleRecord = IDL.Record({
  'id' : IDL.Nat,
  'timing' : IDL.Text,
  'createdAt' : Time,
  'recipientGroups' : NotificationRecipientGroup,
  'channels' : NotificationChannel,
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
  'eventType' : IDL.Text,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Text,
  'paymentGateway' : IDL.Text,
  'timestamp' : Time,
  'monthsPaid' : IDL.Vec(IDL.Text),
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const RCSMessageRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'recipient' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createCredentialRecord' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createNotificationRuleRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        NotificationChannel,
        NotificationRecipientGroup,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'createPaymentRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAttendanceScanRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AttendanceScanRecord)],
      ['query'],
    ),
  'getAttendanceScanRecords' : IDL.Func(
      [],
      [IDL.Vec(AttendanceScanRecord)],
      ['query'],
    ),
  'getCredentialRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CredentialRecord)],
      ['query'],
    ),
  'getCredentialRecords' : IDL.Func([], [IDL.Vec(CredentialRecord)], ['query']),
  'getNotificationRuleRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(NotificationRuleRecord)],
      ['query'],
    ),
  'getNotificationRuleRecords' : IDL.Func(
      [],
      [IDL.Vec(NotificationRuleRecord)],
      ['query'],
    ),
  'getPaymentRecord' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentRecord)], ['query']),
  'getPaymentRecords' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getRCSMessageRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RCSMessageRecord)],
      ['query'],
    ),
  'getRCSMessageRecords' : IDL.Func([], [IDL.Vec(RCSMessageRecord)], ['query']),
  'logAttendanceScan' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'logRCSMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'resetPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateNotificationRuleRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        NotificationChannel,
        NotificationRecipientGroup,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NotificationChannel = IDL.Record({
    'rcs' : IDL.Bool,
    'sms' : IDL.Bool,
    'push' : IDL.Bool,
    'whatsapp' : IDL.Bool,
    'email' : IDL.Bool,
    'inApp' : IDL.Bool,
  });
  const NotificationRecipientGroup = IDL.Record({
    'students' : IDL.Bool,
    'teachers' : IDL.Bool,
    'staff' : IDL.Bool,
    'admins' : IDL.Bool,
    'parents' : IDL.Bool,
  });
  const Time = IDL.Int;
  const AttendanceScanRecord = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Text,
    'scannedBy' : IDL.Text,
    'timestamp' : Time,
    'deviceRole' : IDL.Text,
  });
  const CredentialRecord = IDL.Record({
    'userId' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'hashedPassword' : IDL.Text,
  });
  const NotificationRuleRecord = IDL.Record({
    'id' : IDL.Nat,
    'timing' : IDL.Text,
    'createdAt' : Time,
    'recipientGroups' : NotificationRecipientGroup,
    'channels' : NotificationChannel,
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
    'eventType' : IDL.Text,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Text,
    'paymentGateway' : IDL.Text,
    'timestamp' : Time,
    'monthsPaid' : IDL.Vec(IDL.Text),
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const RCSMessageRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'recipient' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createCredentialRecord' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createNotificationRuleRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          NotificationChannel,
          NotificationRecipientGroup,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'createPaymentRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAttendanceScanRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AttendanceScanRecord)],
        ['query'],
      ),
    'getAttendanceScanRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceScanRecord)],
        ['query'],
      ),
    'getCredentialRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CredentialRecord)],
        ['query'],
      ),
    'getCredentialRecords' : IDL.Func(
        [],
        [IDL.Vec(CredentialRecord)],
        ['query'],
      ),
    'getNotificationRuleRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(NotificationRuleRecord)],
        ['query'],
      ),
    'getNotificationRuleRecords' : IDL.Func(
        [],
        [IDL.Vec(NotificationRuleRecord)],
        ['query'],
      ),
    'getPaymentRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PaymentRecord)],
        ['query'],
      ),
    'getPaymentRecords' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getRCSMessageRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RCSMessageRecord)],
        ['query'],
      ),
    'getRCSMessageRecords' : IDL.Func(
        [],
        [IDL.Vec(RCSMessageRecord)],
        ['query'],
      ),
    'logAttendanceScan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'logRCSMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'resetPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateNotificationRuleRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          NotificationChannel,
          NotificationRecipientGroup,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };