/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    /**
     * / Upsert a batch of records (insert or overwrite by id).
     */
    batchUpsert(collection: string, records: Array<{
        id: string;
        data: string;
    }>): Promise<{
        ok: boolean;
        err: string;
        count: bigint;
    }>;
    /**
     * / Create a new record. Fails if the id already exists.
     */
    createRecord(collection: string, id: string, data: string): Promise<{
        ok: boolean;
        err: string;
    }>;
    /**
     * / Delete an entire collection. Returns number of records removed.
     */
    deleteCollection(collection: string): Promise<{
        ok: boolean;
        count: bigint;
    }>;
    /**
     * / Delete a record by id.
     */
    deleteRecord(collection: string, id: string): Promise<{
        ok: boolean;
        err: string;
    }>;
    /**
     * / Export all data for backup. Returns array of (collection, [(id, data)]).
     */
    exportAll(): Promise<Array<[string, Array<[string, string]>]>>;
    /**
     * / Return changelog entries since a given timestamp (nanoseconds).
     * / Pass 0 to get all entries.
     */
    getChangelog(since: bigint): Promise<Array<string>>;
    /**
     * / Return count per collection.
     */
    getCounts(): Promise<Array<[string, bigint]>>;
    /**
     * / Get a single record by id. Returns null if not found.
     */
    getRecord(collection: string, id: string): Promise<string | null>;
    /**
     * / Import all data from a backup. Merges (upserts) all records.
     */
    importAll(data: Array<[string, Array<[string, string]>]>): Promise<{
        ok: boolean;
        count: bigint;
    }>;
    /**
     * / List all records in a collection as an array of JSON strings.
     */
    listRecords(collection: string): Promise<Array<string>>;
    /**
     * / Paginated list. offset is 0-based.
     */
    listRecordsPaginated(collection: string, offset: bigint, limit: bigint): Promise<{
        total: bigint;
        records: Array<string>;
    }>;
    /**
     * / Health check.
     */
    ping(): Promise<string>;
    /**
     * / Update an existing record. Returns err if not found.
     */
    updateRecord(collection: string, id: string, data: string): Promise<{
        ok: boolean;
        err: string;
    }>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async batchUpsert(arg0: string, arg1: Array<{
        id: string;
        data: string;
    }>): Promise<{
        ok: boolean;
        err: string;
        count: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.batchUpsert(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchUpsert(arg0, arg1);
            return result;
        }
    }
    async createRecord(arg0: string, arg1: string, arg2: string): Promise<{
        ok: boolean;
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCollection(arg0: string): Promise<{
        ok: boolean;
        count: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return result;
        }
    }
    async deleteRecord(arg0: string, arg1: string): Promise<{
        ok: boolean;
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecord(arg0, arg1);
            return result;
        }
    }
    async exportAll(): Promise<Array<[string, Array<[string, string]>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportAll();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportAll();
            return result;
        }
    }
    async getChangelog(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangelog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangelog(arg0);
            return result;
        }
    }
    async getCounts(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCounts();
            return result;
        }
    }
    async getRecord(arg0: string, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecord(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecord(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async importAll(arg0: Array<[string, Array<[string, string]>]>): Promise<{
        ok: boolean;
        count: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.importAll(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importAll(arg0);
            return result;
        }
    }
    async listRecords(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecords(arg0);
            return result;
        }
    }
    async listRecordsPaginated(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        total: bigint;
        records: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecordsPaginated(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecordsPaginated(arg0, arg1, arg2);
            return result;
        }
    }
    async ping(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.ping();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ping();
            return result;
        }
    }
    async updateRecord(arg0: string, arg1: string, arg2: string): Promise<{
        ok: boolean;
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecord(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
