/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    /**
     * / Batch upsert array of JSON records. Returns count upserted.
     */
    batchUpsert(collection: string, recordsJson: Array<string>): Promise<bigint>;
    /**
     * / Create a new record. Returns "ok".
     */
    createRecord(collection: string, recordJson: string): Promise<string>;
    /**
     * / Delete a record by id. Returns "ok" or "not_found".
     */
    deleteRecord(collection: string, id: string): Promise<string>;
    /**
     * / Fetch all collections in one shot (WhatsApp-style initial load).
     */
    fetchAll(): Promise<string>;
    /**
     * / Return recent changelog entries as JSON array (last 100)
     */
    getChangelog(): Promise<string>;
    /**
     * / Return record counts for all collections (for dashboard stats)
     */
    getCounts(): Promise<string>;
    /**
     * / Return a single record by id (JSON string or empty string if not found)
     */
    getRecord(collection: string, id: string): Promise<string>;
    /**
     * / Return all records in a collection as a JSON array string
     */
    listRecords(collection: string): Promise<string>;
    ping(): Promise<string>;
    /**
     * / Replace entire collection with new records. Returns count.
     */
    replaceCollection(collection: string, recordsJson: Array<string>): Promise<bigint>;
    /**
     * / Update an existing record by id. Returns "ok" or "not_found".
     */
    updateRecord(collection: string, id: string, recordJson: string): Promise<string>;
    /**
     * / Upsert a record: update if id exists, create otherwise. Returns "ok".
     */
    upsertRecord(collection: string, id: string, recordJson: string): Promise<string>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async batchUpsert(arg0: string, arg1: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.batchUpsert(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchUpsert(arg0, arg1);
            return result;
        }
    }
    async createRecord(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecord(arg0, arg1);
            return result;
        }
    }
    async deleteRecord(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecord(arg0, arg1);
            return result;
        }
    }
    async fetchAll(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAll();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAll();
            return result;
        }
    }
    async getChangelog(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangelog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangelog();
            return result;
        }
    }
    async getCounts(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCounts();
            return result;
        }
    }
    async getRecord(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecord(arg0, arg1);
            return result;
        }
    }
    async listRecords(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecords(arg0);
            return result;
        }
    }
    async ping(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.ping();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ping();
            return result;
        }
    }
    async replaceCollection(arg0: string, arg1: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.replaceCollection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replaceCollection(arg0, arg1);
            return result;
        }
    }
    async updateRecord(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async upsertRecord(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertRecord(arg0, arg1, arg2);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
