/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface NotificationRuleRecord {
    id: bigint;
    timing: string;
    createdAt: Time;
    recipientGroups: NotificationRecipientGroup;
    channels: NotificationChannel;
    isActive: boolean;
    updatedAt: Time;
    eventType: string;
}
export interface AttendanceScanRecord {
    id: bigint;
    studentId: string;
    scannedBy: string;
    timestamp: Time;
    deviceRole: string;
}
export interface PaymentRecord {
    id: bigint;
    studentId: string;
    paymentGateway: string;
    timestamp: Time;
    monthsPaid: Array<string>;
    amount: bigint;
    receiptNumber: string;
}
export interface RCSMessageRecord {
    id: bigint;
    status: string;
    recipient: string;
    message: string;
    timestamp: Time;
}
export interface CredentialRecord {
    userId: string;
    createdAt: Time;
    updatedAt: Time;
    hashedPassword: string;
}
export interface NotificationRecipientGroup {
    students: boolean;
    teachers: boolean;
    staff: boolean;
    admins: boolean;
    parents: boolean;
}
export interface NotificationChannel {
    rcs: boolean;
    sms: boolean;
    push: boolean;
    whatsapp: boolean;
    email: boolean;
    inApp: boolean;
}
export interface backendInterface {
    createCredentialRecord(userId: string, hashedPassword: string): Promise<void>;
    createNotificationRuleRecord(eventType: string, timing: string, channels: NotificationChannel, recipientGroups: NotificationRecipientGroup, isActive: boolean): Promise<bigint>;
    createPaymentRecord(studentId: string, amount: bigint, monthsPaid: Array<string>, paymentGateway: string, receiptNumber: string): Promise<bigint>;
    getAttendanceScanRecord(id: bigint): Promise<AttendanceScanRecord | null>;
    getAttendanceScanRecords(): Promise<Array<AttendanceScanRecord>>;
    getCredentialRecord(userId: string): Promise<CredentialRecord | null>;
    getCredentialRecords(): Promise<Array<CredentialRecord>>;
    getNotificationRuleRecord(id: bigint): Promise<NotificationRuleRecord | null>;
    getNotificationRuleRecords(): Promise<Array<NotificationRuleRecord>>;
    getPaymentRecord(id: bigint): Promise<PaymentRecord | null>;
    getPaymentRecords(): Promise<Array<PaymentRecord>>;
    getRCSMessageRecord(id: bigint): Promise<RCSMessageRecord | null>;
    getRCSMessageRecords(): Promise<Array<RCSMessageRecord>>;
    logAttendanceScan(studentId: string, scannedBy: string, deviceRole: string): Promise<bigint>;
    logRCSMessage(recipient: string, message: string, status: string): Promise<bigint>;
    resetPassword(userId: string, newHashedPassword: string): Promise<void>;
    updateNotificationRuleRecord(id: bigint, eventType: string, timing: string, channels: NotificationChannel, recipientGroups: NotificationRecipientGroup, isActive: boolean): Promise<void>;
}
import type { AttendanceScanRecord as _AttendanceScanRecord, CredentialRecord as _CredentialRecord, NotificationRuleRecord as _NotificationRuleRecord, PaymentRecord as _PaymentRecord, RCSMessageRecord as _RCSMessageRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCredentialRecord(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCredentialRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCredentialRecord(arg0, arg1);
            return result;
        }
    }
    async createNotificationRuleRecord(arg0: string, arg1: string, arg2: NotificationChannel, arg3: NotificationRecipientGroup, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotificationRuleRecord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotificationRuleRecord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPaymentRecord(arg0: string, arg1: bigint, arg2: Array<string>, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentRecord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentRecord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAttendanceScanRecord(arg0: bigint): Promise<AttendanceScanRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceScanRecord(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceScanRecord(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceScanRecords(): Promise<Array<AttendanceScanRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceScanRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceScanRecords();
            return result;
        }
    }
    async getCredentialRecord(arg0: string): Promise<CredentialRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCredentialRecord(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCredentialRecord(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCredentialRecords(): Promise<Array<CredentialRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCredentialRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCredentialRecords();
            return result;
        }
    }
    async getNotificationRuleRecord(arg0: bigint): Promise<NotificationRuleRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationRuleRecord(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationRuleRecord(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationRuleRecords(): Promise<Array<NotificationRuleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationRuleRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationRuleRecords();
            return result;
        }
    }
    async getPaymentRecord(arg0: bigint): Promise<PaymentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentRecord(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentRecord(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentRecords(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentRecords();
            return result;
        }
    }
    async getRCSMessageRecord(arg0: bigint): Promise<RCSMessageRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRCSMessageRecord(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRCSMessageRecord(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRCSMessageRecords(): Promise<Array<RCSMessageRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRCSMessageRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRCSMessageRecords();
            return result;
        }
    }
    async logAttendanceScan(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logAttendanceScan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logAttendanceScan(arg0, arg1, arg2);
            return result;
        }
    }
    async logRCSMessage(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logRCSMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logRCSMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async resetPassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPassword(arg0, arg1);
            return result;
        }
    }
    async updateNotificationRuleRecord(arg0: bigint, arg1: string, arg2: string, arg3: NotificationChannel, arg4: NotificationRecipientGroup, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotificationRuleRecord(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotificationRuleRecord(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceScanRecord]): AttendanceScanRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CredentialRecord]): CredentialRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NotificationRuleRecord]): NotificationRuleRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentRecord]): PaymentRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RCSMessageRecord]): RCSMessageRecord | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
